### ISSUE TITLE
Find fails on hidden fields

### ISSUE THREAD

**Issue by ChipCoons** [philss/floki#279] opened 2020-06-12 18:48 UTC
## Description

When using Floki.find(fragment, "#name) where name is the name of an attribute of type="hidden", an empty list is returned.

## To Reproduce

- Using Floki v0.26.0
- Using Elixir v1.10.3
- Using Erlang OTP v22
- With this code:
  ```elixir
  # body is the html body performed on a 'GET' on https://secure.utah.gov/llv/search/index.html
    f_body = Floki.parse_document!(body)
    div = Floki.find(f_body, "#searchName")
    form_body = Floki.find(div, "#command")
    csrf_element = Floki.find(form_body, "#_csrf")

  # element in the testing sample:
  `<input type="hidden" name="_csrf" value="2736e8e5-7c83-49c1-922e-e00a8fa967e5">`
  ```
## Actual Result
[]

## Expected behavior
[
  {"input",
   [
     {"type", "hidden"},
     {"value", "2736e8e5-7c83-49c1-922e-e00a8fa967e5"},
     {"name", "_csrf"}
   ], [] }
]

If I use the find function on any non-hidden, named field, I get the expected results.

**Comment by philss** [comment] 2020-06-12 22:13
@ChipCoons thank you for open the issue. I believe the problem is that you are using a `ID selector` instead of a `attribute selector` targeting the `name="_csrf"`.

Please try this:

```elixir
Floki.find(form_body, "input[name=_csrf]")
```

I'm closing the issue.

**Closed by philss** 2020-06-12 22:13 UTC
Labels: Bug

**Comment by ChipCoons** [comment] 2020-06-13 03:21
That worked.  Thanks.  Thanks for making a great library as well.

-Chip
