### ISSUE TITLE
Floki.text doesn't find text in array of simple text nodes

### ISSUE THREAD

**Issue by boydm** [philss/floki#91] opened 2017-02-05 04:11 UTC
In version 0.9,
`Floki.text(["hello world"])` would return `"hello world"`

In version 0.13,
`Floki.text(["hello world"])` returns `""`
note that
`Floki.text([{"div", [], ["hello world"]}])` returns `"hello world"`

This is an issue when I've already drilled down into the div and I just want to get the text of its children. A bug or is there an updated syntax?

**Comment by philss** [comment] 2017-02-05 05:37
@boydm thank you for open the issue. I will try to take a look tomorrow.

**Comment by boydm** [comment] 2017-02-07 18:31
fyi
`Floki.FlatText.get(["hello world"])` does return `"hello world"`

**Comment by philss** [comment] 2017-02-08 00:36
@boydm this is definitely a bug introduced in version 0.13. The problem is that now Floki builds a representation of HTML tree using a map with references to its children nodes. For the case of a HTML tree that contains with only text as root nodes Floki is [ignoring those nodes](https://github.com/philss/floki/blob/d861fadc8f9fc2f8b3d7e3949336f769311c8633/lib/floki/html_tree.ex#L35).

I will try to fix this soon. Thanks again!

**Comment by philss** [comment] 2017-02-08 01:14
@boydm this bug is fixed in version `0.13.2`. Please update to that version. Thanks!

**Closed by philss** 2017-02-08 01:14 UTC
Labels: Bug

**Comment by boydm** [comment] 2017-02-08 20:19
Thank you very much!
